version: '3.8'

services:
  # Service Backend (Flask)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: klub-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/cours:/app/cours
      - ./backend/flash-cards:/app/flash-cards
      - ./backend/ecole_direct_config.json:/app/ecole_direct_config.json
    expose:
      - "5000"          # Interne uniquement, pas expos√© sur le VPS
    restart: unless-stopped
    networks:
      - klub-network

  # Service Frontend (Angular + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: klub-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - klub-network

networks:
  klub-network:
    driver: bridge