version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: klub-backend
    environment:
      - FLASK_ENV=production
    expose:
      - "5000"          # plus expos√© publiquement, Nginx fait le relais
    restart: unless-stopped
    networks:
      - klub-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: klub-frontend
    ports:
      - "127.0.0.1:4200:80"   # uniquement accessible en local par Nginx
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - klub-network

networks:
  klub-network:
    driver: bridge